version: "3"
services:
  web:
     image: apache
     build: ./webapp
     container_name: apache_web
     restart: always
     ports:
       - "500:80"
#colon ke baad waala 80 is dockerfile waala to be used for local host
